id: P9C33C29C
initial_creation_type: input
source_metadata:
  title: Smṛtijñānakīrti
  language: bo
  description: 'Texts by and about the famous 11th-century Indian paṇḍita Smṛtijñānakīrti
    (dran pa''i ye shes grags pa):'
  volume:
    0d5cae5d2d704b50aecc4a58fc218b0b:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    9260648836184969826eb4b9c7eed006:
      title: 'Intensely Brilliant Wisdom: In Praise of the Great Elder Smṛtijñāna'
      parent: Praise
    62e8bb0c7458492f8aed09588110ba8f:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
created_at: '2022-03-01T02:24:30.277181'
last_modified_at: '2022-03-01T02:24:30.277184'
